### ISSUE TITLE
Finished job returning state "NOT CREATED"

### ISSUE THREAD

**Issue by IgorVictor** [fogbow/arrebol#46] opened 2017-05-16 13:27 UTC
To reproduce:

Create a simple job (sleepjob would do)
Submit it to arrebol
Wait for completion
It will go to state NOTCREATED when queried

**Comment by hukasu** [comment] 2017-09-18 18:50
Duplicate of #47 
Probably the same cause as stated above

**Closed as completed by hukasu** 2017-09-18 18:50 UTC
